services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: kemlak
      POSTGRES_PASSWORD: kemlak_sifre
      POSTGRES_DB: kemlak_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
