"""listing tablosu guncell

Revision ID: 1fbb60c8bdd9
Revises: 38183fc216b0
Create Date: 2026-07-10 10:54:00.373368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fbb60c8bdd9'
down_revision: Union[str, Sequence[str], None] = '38183fc216b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    cephe_enum = sa.Enum('KUZEY', 'GUNEY', 'DOGU', 'BATI', name='cephe')
    cephe_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('listings', sa.Column('cephe', cephe_enum, nullable=False))

    isitma_tipi_enum = sa.Enum(
        'KOMBI', 'KLIMA', 'MERKEZI', 'MERKEZI_PAY_OLCER', 'SOBA', 'KAT_KALORIFERI',
        'GUNES_ENERJISI', 'JEOTERMAL_ISITMA', 'YERDEN_ISITMA', 'DOGALGAZ_SOBASI',
        'FANCOIL_UNITESI', 'VRV', 'ISI_POMPASI', 'SOMINE', 'ISITMA_YOK', 'BELIRTILMEMIS',
        name='isitma_tipi_enum',
    )
    isitma_tipi_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('listings', 'isitma_tipi',
               existing_type=sa.VARCHAR(length=50),
               type_=isitma_tipi_enum,
               postgresql_using='isitma_tipi::isitma_tipi_enum',
               existing_nullable=False)

    kullanim_durumu_enum = sa.Enum('MULK_SAHIBI', 'BOS', 'KIRACILI', name='kullanim_durumu_enum')
    kullanim_durumu_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('listings', 'kullanim_durumu',
               existing_type=sa.VARCHAR(length=20),
               type_=kullanim_durumu_enum,
               postgresql_using='kullanim_durumu::kullanim_durumu_enum',
               existing_nullable=False)

    op.drop_constraint(op.f('listings_kaynak_url_key'), 'listings', type_='unique')
    op.drop_column('listings', 'kaynak_url')
    op.drop_column('listings', 'kaynak_site')
    op.drop_column('listings', 'tapu_durumu')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('tapu_durumu', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('kaynak_site', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('kaynak_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('listings_kaynak_url_key'), 'listings', ['kaynak_url'], postgresql_nulls_not_distinct=False)
    op.alter_column('listings', 'kullanim_durumu',
               existing_type=sa.Enum('MULK_SAHIBI', 'BOS', 'KIRACILI', name='kullanim_durumu_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('listings', 'isitma_tipi',
               existing_type=sa.Enum('KOMBI', 'KLIMA', 'MERKEZI', 'MERKEZI_PAY_OLCER', 'SOBA', 'KAT_KALORIFERI', 'GUNES_ENERJISI', 'JEOTERMAL_ISITMA', 'YERDEN_ISITMA', 'DOGALGAZ_SOBASI', 'FANCOIL_UNITESI', 'VRV', 'ISI_POMPASI', 'SOMINE', 'ISITMA_YOK', 'BELIRTILMEMIS', name='isitma_tipi_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('listings', 'cephe_kuzey')
    # ### end Alembic commands ###
