"""csv verisinden kaynakli guncelleme

Revision ID: 32eeb5351a15
Revises: 554785c2d630
Create Date: 2026-07-17 14:46:10.964246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32eeb5351a15'
down_revision: Union[str, Sequence[str], None] = '554785c2d630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'banyo_sayisi',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('listings', 'kat_sayisi',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'kat_sayisi',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('listings', 'banyo_sayisi',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
