"""update listing table

Revision ID: 38183fc216b0
Revises: 520db1c2ac15
Create Date: 2026-07-10 10:02:50.084864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38183fc216b0'
down_revision: Union[str, Sequence[str], None] = '520db1c2ac15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('ilan_no', sa.String(length=50), nullable=False))
    op.add_column('listings', sa.Column('il', sa.String(length=50), nullable=False))
    op.add_column('listings', sa.Column('ilce', sa.String(length=50), nullable=False))
    op.add_column('listings', sa.Column('mahalle', sa.String(length=100), nullable=True))
    op.add_column('listings', sa.Column('brut_metrekare', sa.Integer(), nullable=False))
    op.add_column('listings', sa.Column('bulundugu_kat', sa.String(length=20), nullable=False))
    op.add_column('listings', sa.Column('isitma_tipi', sa.String(length=50), nullable=False))
    op.add_column('listings', sa.Column('esyali', sa.Boolean(), nullable=False))
    op.add_column('listings', sa.Column('kullanim_durumu', sa.String(length=20), nullable=False))
    op.add_column('listings', sa.Column('tapu_durumu', sa.String(length=50), nullable=False))
    op.add_column('listings', sa.Column('aidat', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('kaynak_url', sa.String(length=500), nullable=False))
    op.alter_column('listings', 'fiyat',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using='fiyat::integer',
               existing_nullable=False)
    op.alter_column('listings', 'oda_sayisi',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.create_index(op.f('ix_listings_fiyat'), 'listings', ['fiyat'], unique=False)
    op.create_index(op.f('ix_listings_il'), 'listings', ['il'], unique=False)
    op.create_index(op.f('ix_listings_ilce'), 'listings', ['ilce'], unique=False)
    op.create_unique_constraint(None, 'listings', ['kaynak_url'])
    op.drop_column('listings', 'otoparkli_mi')
    op.drop_column('listings', 'ilce_adi')
    op.drop_column('listings', 'sitede_mi')
    op.drop_column('listings', 'brut_metrakare')
    op.drop_column('listings', 'esyali_mi')
    op.drop_column('listings', 'ilan_id')
    op.drop_column('listings', 'asansorlu_mu')
    op.drop_column('listings', 'il_adi')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('il_adi', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('asansorlu_mu', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('ilan_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('esyali_mi', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('brut_metrakare', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('sitede_mi', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('ilce_adi', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('otoparkli_mi', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint('listings_kaynak_url_key', 'listings', type_='unique')
    op.drop_index(op.f('ix_listings_ilce'), table_name='listings')
    op.drop_index(op.f('ix_listings_il'), table_name='listings')
    op.drop_index(op.f('ix_listings_fiyat'), table_name='listings')
    op.alter_column('listings', 'oda_sayisi',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('listings', 'fiyat',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('listings', 'kaynak_url')
    op.drop_column('listings', 'aidat')
    op.drop_column('listings', 'tapu_durumu')
    op.drop_column('listings', 'kullanim_durumu')
    op.drop_column('listings', 'esyali')
    op.drop_column('listings', 'isitma_tipi')
    op.drop_column('listings', 'bulundugu_kat')
    op.drop_column('listings', 'brut_metrekare')
    op.drop_column('listings', 'mahalle')
    op.drop_column('listings', 'ilce')
    op.drop_column('listings', 'il')
    op.drop_column('listings', 'ilan_no')
    # ### end Alembic commands ###
