"""kaynak_url alanini geri ekle

Revision ID: 403be4a60bde
Revises: 50d2461fc90f
Create Date: 2026-07-14 11:38:23.784597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403be4a60bde'
down_revision: Union[str, Sequence[str], None] = '50d2461fc90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('kaynak_url', sa.String(length=500), nullable=False))
    op.create_unique_constraint(None, 'listings', ['kaynak_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='unique')
    op.drop_column('listings', 'kaynak_url')
    # ### end Alembic commands ###
