"""son hali cidden

Revision ID: 50d2461fc90f
Revises: ccac7d207c6a
Create Date: 2026-07-10 11:10:17.778673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50d2461fc90f'
down_revision: Union[str, Sequence[str], None] = 'ccac7d207c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('cephe', sa.Enum('KUZEY', 'GUNEY', 'DOGU', 'BATI', name='cephe'), nullable=False))
    op.drop_column('listings', 'cephe_kuzey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('cephe_kuzey', postgresql.ENUM('KUZEY', 'GUNEY', 'DOGU', 'BATI', name='cephe'), autoincrement=False, nullable=False))
    op.drop_column('listings', 'cephe')
    # ### end Alembic commands ###
