"""create listings table

Revision ID: 520db1c2ac15
Revises: 
Create Date: 2026-07-10 09:10:18.203437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520db1c2ac15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ilan_id', sa.Integer(), nullable=False),
    sa.Column('il_adi', sa.String(), nullable=False),
    sa.Column('ilce_adi', sa.String(), nullable=False),
    sa.Column('fiyat', sa.String(), nullable=False),
    sa.Column('oda_sayisi', sa.Integer(), nullable=False),
    sa.Column('kat_sayisi', sa.Integer(), nullable=False),
    sa.Column('banyo_sayisi', sa.Integer(), nullable=False),
    sa.Column('brut_metrakare', sa.Integer(), nullable=False),
    sa.Column('net_metrekare', sa.Integer(), nullable=False),
    sa.Column('bina_yasi', sa.Integer(), nullable=False),
    sa.Column('esyali_mi', sa.Boolean(), nullable=False),
    sa.Column('otoparkli_mi', sa.Boolean(), nullable=False),
    sa.Column('asansorlu_mu', sa.Boolean(), nullable=False),
    sa.Column('sitede_mi', sa.Boolean(), nullable=False),
    sa.Column('kaynak_site', sa.String(), nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listings')
    # ### end Alembic commands ###
