"""sutunlar guncellendi

Revision ID: 554785c2d630
Revises: b65c1810537e
Create Date: 2026-07-14 12:36:09.488609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554785c2d630'
down_revision: Union[str, Sequence[str], None] = 'b65c1810537e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'banyo_sayisi',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('listings', 'kat_sayisi',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'kat_sayisi',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('listings', 'banyo_sayisi',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
