"""valuations tablosu

Revision ID: 7b8cd5ed3ccf
Revises: 32eeb5351a15
Create Date: 2026-07-21 09:35:56.576807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8cd5ed3ccf'
down_revision: Union[str, Sequence[str], None] = '32eeb5351a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ilce', sa.String(length=50), nullable=False),
    sa.Column('mahalle', sa.String(length=100), nullable=True),
    sa.Column('brut_m2', sa.Integer(), nullable=False),
    sa.Column('net_m2', sa.Integer(), nullable=False),
    sa.Column('oda_sayisi', sa.String(length=20), nullable=True),
    sa.Column('banyo_sayisi', sa.Integer(), nullable=False),
    sa.Column('bina_yasi', sa.Integer(), nullable=False),
    sa.Column('bulundugu_kat', sa.String(length=20), nullable=True),
    sa.Column('kat_sayisi', sa.Integer(), nullable=False),
    sa.Column('isinma', sa.String(length=50), nullable=True),
    sa.Column('cephe', sa.String(length=50), nullable=True),
    sa.Column('esya_durumu', sa.String(length=50), nullable=True),
    sa.Column('aidat', sa.Integer(), nullable=False),
    sa.Column('tahmini_fiyat', sa.Integer(), nullable=False),
    sa.Column('birim_m2_fiyat', sa.Integer(), nullable=False),
    sa.Column('fiyat_alt', sa.Integer(), nullable=False),
    sa.Column('fiyat_ust', sa.Integer(), nullable=False),
    sa.Column('beklenen_fiyat', sa.Integer(), nullable=True),
    sa.Column('yorum_durum', sa.String(length=20), nullable=True),
    sa.Column('olusturulma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuations_ilce'), 'valuations', ['ilce'], unique=False)
    op.create_index(op.f('ix_valuations_olusturulma_tarihi'), 'valuations', ['olusturulma_tarihi'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valuations_olusturulma_tarihi'), table_name='valuations')
    op.drop_index(op.f('ix_valuations_ilce'), table_name='valuations')
    op.drop_table('valuations')
    # ### end Alembic commands ###
