"""cephe boolean, kaynak_url, kullanim belirtilmemis

Revision ID: b65c1810537e
Revises: 403be4a60bde
Create Date: 2026-07-14 12:01:30.710640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b65c1810537e'
down_revision: Union[str, Sequence[str], None] = '403be4a60bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('listings', sa.Column('cephe_kuzey', sa.Boolean(), nullable=False))
    op.add_column('listings', sa.Column('cephe_guney', sa.Boolean(), nullable=False))
    op.add_column('listings', sa.Column('cephe_dogu', sa.Boolean(), nullable=False))
    op.add_column('listings', sa.Column('cephe_bati', sa.Boolean(), nullable=False))
    op.alter_column('listings', 'bulundugu_kat',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('listings', 'cephe')
    op.execute("DROP TYPE IF EXISTS cephe")
    op.execute("ALTER TYPE kullanim_durumu_enum ADD VALUE IF NOT EXISTS 'BELIRTILMEMIS'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('cephe', postgresql.ENUM('KUZEY', 'GUNEY', 'DOGU', 'BATI', name='cephe'), autoincrement=False, nullable=False))
    op.alter_column('listings', 'bulundugu_kat',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('listings', 'cephe_bati')
    op.drop_column('listings', 'cephe_dogu')
    op.drop_column('listings', 'cephe_guney')
    op.drop_column('listings', 'cephe_kuzey')
    # ### end Alembic commands ###
